#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/terminaldotshop/terminal-sdk-go,github.com/stainless-sdks/terminal-go"

go build -o terraform-provider-terminal
