#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/terminaldotshop/terminal-sdk-go,github.com/stainless-sdks/terminal-go"

REPLACEMENT="${1:-"../terminal-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/terminaldotshop/terminal-sdk-go="$REPLACEMENT"
go mod tidy -e
