#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/terminaldotshop/terminal-sdk-go,github.com/stainless-sdks/terminal-go"

echo "==> Running tests"
go test ./... "$@"
